### ISSUE TITLE
jquery lockfixed not working

### ISSUE THREAD

**Issue by rich11** [ymschaap/jquery-lockfixed#1]
I'm new to jquery and javascript and are trying to get lockfixed to work. I keep getting this error, 
Uncaught TypeError: Object function (a,b){return new c.fn.init(a,b)} has no method 'lockfixed' 
I think it has something to do with the jquery extend function, I can't figure out how or why. I have stepped though my code and the Demo code simultaneously, everything looks the same, except the Demo works and mine does not.

Any help will be appreciated.
Richard.

**Comment by treeguy** [comment]
I am having a similar problem, but much more basic. Uploaded the source code of the LockFixed demo file to my server (https://store.advancedtree.com/agora.cgi?cartlink=DEMO-Lockfixed.shtm; I put jquery.lockfixed.js in that directory, also), but it does not work.  BTW, I changed the demo file's extension to *.shtm because the site has code that automatically populates a menu from any *.htm or *.html files. Am I missing a needed path declaration or something?
Thanks in advance, 
John
