### ISSUE TITLE
How to disable on mobile?

### ISSUE THREAD

**Issue by ChongoShaun** [ymschaap/jquery-lockfixed#12]
This script is nice and simple and works well. I implemented your fluid updates and it really does work! The one issue though is that when shrinking the browser, my responsive site stacks the elements and I would like the fixed element to unlock itself. Is there any simple techniques for this?

**Comment by starleen-lp** [comment]
I have almost the same issue - on mobile it just doesn't let me scroll what so ever. I want to disable it on mobile and tablet (anything under 1024px).

**Comment by ymschaap** [comment]
What you can do is, after line [#53](https://github.com/ymschaap/jquery-lockfixed/blob/master/jquery.lockfixed.js#L53):

```
// if browser has touch screen and screen width is (reduced to) under 750 pixels
if( ('ontouchstart' in window && document.documentElement.clientWidth < 750 ) {
    // reset element to original value (not fixed!)
    el.css({
        'position': el_position,
        'top': el_position_top,
        'width': el_width + "px",
        'marginTop': (el_margin_top ? el_margin_top : 0) + "px"
    });
    return;
}
```

I did not test this, but it should work. 

It makes sense to have this as a setting, which I might implement or you can PR.

**Comment by starleen-lp** [comment]
Hey, this is perfect! I tested it and it works like a charm! You just have one extra parentesis after the if statement. Also, for the needs of my project I changed the clientWidth to <=768, so it matches my other brakepoints. I haven't tested it on a 10 inch tablet (like the Galaxy Tab10), because I feel like it would have a problem there, because it's resolution is 800x1024px, but that can be easily fixed now.
Thank you very much!
